error: add Kind for inability to retreive a tree
We plan to introduce facilties for retrieving git trees in the future.
This change introduces an error `Kind` for errors related to that.