error: add Kind for failure to create a tree builder
We plan to introduce facilties for building git trees in the future.
This change introduces an error `Kind` for errors related to that.