error: make Inner public
We meant to keep `Inner` private, but we rely on it for error
conversion, and we do need to specify this also in public bounds.
Thus, we make it public after all.