error: add Kind for failure to retrieve a signature
We plan to introduce fns for retrieving git signatures in the future.
This change introduces an error `Kind` for errors related to that.