error: add fn for trait object retrieval to Inner
If we want to impl `std::error::Error::source` for `Error`, which we do,
we need to view the inner error type as a trait object. We previously
did this in the fn impl, but this should rather go into a fn associated
to `Inner` itself.