error: allow Error to carry an Utf8Error as inner error
We currently hide any errors generated in fns associated to some traits,
including `reference::Reference` and `remote::Name`. We want to change
that and communicate those inner errors. This will also require
converting those errors to `error::Error`, or rather wrapping them.

At least for `git2`, those errors are usually related to conversion of
byte slices to `&str`. And `std::str::Utf8Error` is conventional enough
that wrapping it wouldn't seem out of place.